package service

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/magicalcosmos/goblogssr/graph/dao"
	"github.com/magicalcosmos/goblogssr/graph/generated"
	"github.com/magicalcosmos/goblogssr/graph/model"
)

// Enquiries is the resolver for the enquiries field.
func (r *enquiryWithPageResolver) Enquiries(ctx context.Context, obj *model.EnquiryWithPage) ([]*model.Enquiry, error) {
	panic(fmt.Errorf("not implemented: Enquiries - enquiries"))
}

// Page is the resolver for the page field.
func (r *enquiryWithPageResolver) Page(ctx context.Context, obj *model.EnquiryWithPage) (*model.Page, error) {
	panic(fmt.Errorf("not implemented: Page - page"))
}

// SaveEnquiry is the resolver for the saveEnquiry field.
func (r *mutationResolver) SaveEnquiry(ctx context.Context, input model.NewEnquiry) (*model.Enquiry, error) {
	var enquiry = &model.Enquiry{
		Name:    *input.Name,
		Email:   *input.Email,
		Phone:   *input.Phone,
		Type:    *input.Type,
		Message: *input.Message,
	}
	return dao.SaveEnquiry(enquiry), nil
}

// EnquiryList is the resolver for the enquiryList field.
func (r *queryResolver) EnquiryList(ctx context.Context, input model.Q) (*model.EnquiryWithPage, error) {
	panic(fmt.Errorf("not implemented: EnquiryList - enquiryList"))
}

// EnquiryWithPage returns generated.EnquiryWithPageResolver implementation.
func (r *Resolver) EnquiryWithPage() generated.EnquiryWithPageResolver {
	return &enquiryWithPageResolver{r}
}

type enquiryWithPageResolver struct{ *Resolver }
