package service

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/magicalcosmos/goblogssr/graph/dao"
	"github.com/magicalcosmos/goblogssr/graph/generated"
	"github.com/magicalcosmos/goblogssr/graph/model"
)

// Name is the resolver for the name field.
func (r *enquiryResolver) Name(ctx context.Context, obj *model.Enquiry) (string, error) {
	panic(fmt.Errorf("not implemented: Name - name"))
}

// Email is the resolver for the email field.
func (r *enquiryResolver) Email(ctx context.Context, obj *model.Enquiry) (string, error) {
	panic(fmt.Errorf("not implemented: Email - email"))
}

// Enquiries is the resolver for the enquiries field.
func (r *enquiryWithPageResolver) Enquiries(ctx context.Context, obj *model.EnquiryWithPage) ([]*model.Enquiry, error) {
	panic(fmt.Errorf("not implemented: Enquiries - enquiries"))
}

// Page is the resolver for the page field.
func (r *enquiryWithPageResolver) Page(ctx context.Context, obj *model.EnquiryWithPage) (*model.Page, error) {
	panic(fmt.Errorf("not implemented: Page - page"))
}

// SaveEnquiry is the resolver for the saveEnquiry field.
func (r *mutationResolver) SaveEnquiry(ctx context.Context, input model.NewEnquiry) (*model.Enquiry, error) {
	var enquiry = &model.Enquiry{
		Name:    *input.Name,
		Email:   *input.Email,
		Phone:   *input.Phone,
		Type:    *input.Type,
		Message: *input.Message,
	}
	return dao.SaveEnquiry(enquiry), nil
}

// EnquiryList is the resolver for the EnquiryList field.
func (r *queryResolver) EnquiryList(ctx context.Context, input model.Q) (*model.EnquiryWithPage, error) {
	panic(fmt.Errorf("not implemented: EnquiryList - EnquiryList"))
}

// Enquiry returns generated.EnquiryResolver implementation.
func (r *Resolver) Enquiry() generated.EnquiryResolver { return &enquiryResolver{r} }

// EnquiryWithPage returns generated.EnquiryWithPageResolver implementation.
func (r *Resolver) EnquiryWithPage() generated.EnquiryWithPageResolver {
	return &enquiryWithPageResolver{r}
}

type enquiryResolver struct{ *Resolver }
type enquiryWithPageResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *enquiryResolver) Type(ctx context.Context, obj *model.Enquiry) (int, error) {
	panic(fmt.Errorf("not implemented: Type - type"))
}
func (r *enquiryResolver) Message(ctx context.Context, obj *model.Enquiry) (int, error) {
	panic(fmt.Errorf("not implemented: Message - message"))
}
func (r *enquiryWithPageResolver) Users(ctx context.Context, obj *model.EnquiryWithPage) ([]*model.Enquiry, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}
