// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewArticle struct {
	ID        *string `json:"id,omitempty"`
	AuthorID  *int    `json:"authorId,omitempty"`
	ParentID  *int    `json:"parentId,omitempty"`
	Title     *string `json:"title,omitempty"`
	Brief     *string `json:"brief,omitempty"`
	Content   *string `json:"content,omitempty"`
	Published *int    `json:"published,omitempty"`
	Tag       *string `json:"tag,omitempty"`
	Pv        *int    `json:"pv,omitempty"`
	Review    *int    `json:"review,omitempty"`
	Recommend *int    `json:"recommend,omitempty"`
	Like      *int    `json:"like,omitempty"`
	Status    *int    `json:"status,omitempty"`
}

type NewCategory struct {
	ID       *string `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	ParentID *int    `json:"parentId,omitempty"`
	Sort     *int    `json:"sort,omitempty"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
